### ISSUE TITLE
Solution diverging at nth iteration : global_flexible setup

### ISSUE THREAD

**Issue by sb4233** [team-ocean/veros#669]
While running the [`global_flexible.py`](https://github.com/team-ocean/veros/blob/59afcbee0b77fe1535aa49b0e0a228f50877ac17/veros/setups/global_flexible/global_flexible.py#L1-L417) setup using a single GPU, I got the below error: 

```bash
Traceback (most recent call last):
  File "/home/joy/anaconda3/bin/veros", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/veros/veros/cli/veros_run.py", line 87, in run
    sim.run()
  File "/home/joy/veros/veros/veros.py", line 355, in run
    self.step(self.state)
  File "/home/joy/veros/veros/routines.py", line 215, in __call__
    out = self.function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/veros/veros/veros.py", line 312, in step
    raise RuntimeError(f"solution diverged at iteration {vs.itt}")
RuntimeError: solution diverged at iteration 2979522
srun: error: gpu1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/joy/veros/veros/cli/veros_resubmit.py", line 64, in call_veros
    subprocess.check_call(unparse(cmd + args), shell=True)
  File "/home/joy/anaconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'srun -- veros run global_flexible.py -b jax -n 1 1 --device gpu -s identifier Globalflex_gpu.0000 -s restart_output_filename '{identifier}.restart.h5' -s runlen 3153600000.0' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joy/anaconda3/bin/veros", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joy/veros/veros/cli/veros_resubmit.py", line 125, in cli
    resubmit(*args, **kwargs)
  File "/home/joy/veros/veros/cli/veros_resubmit.py", line 81, in resubmit
    call_veros(veros_cmd, identifier, current_n, length_per_run)
  File "/home/joy/veros/veros/cli/veros_resubmit.py", line 66, in call_veros
    raise RuntimeError(f"Run {n} failed, exiting")
RuntimeError: Run 0 failed, exiting
```

**Comment by dionhaefner** [comment]
Could you try the script in https://github.com/jax-ml/jax/issues/22382 to see if you can reproduce that issue in your specific setup?

**Comment by sb4233** [comment]
> Could you try the script in [jax-ml/jax#22382](https://github.com/jax-ml/jax/issues/22382) to see if you can reproduce that issue in your specific setup?

Yes, I could reproduce the output: 
```python
maskU
1.0
eek
```

**Comment by dionhaefner** [comment]
Thanks! Is that with most recent JAX?

**Comment by sb4233** [comment]
> Thanks! Is that with most recent JAX?

Yes, `v0.4.35`

```python
jax:    0.4.35
jaxlib: 0.4.34
numpy:  1.26.0
python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
jax.devices (1 total): [CudaDevice(id=0)]
platform: uname_result(system='Linux', node='gpu1', release='5.4.0-172-generic', version='#190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024', machine='x86_64')
```

**Comment by dionhaefner** [comment]
Thanks, let me ping the JAX folks about this.

In the meantime, running on CPU is the only workaround unfortunately.

**Comment by dionhaefner** [comment]
@sb4233 Looks like this was fixed upstream. Want to give it a try whether JAX 0.4.37 fixes the issue?

**Comment by dionhaefner** [comment]
Alternatively @nutrik

**Comment by sb4233** [comment]
> @sb4233 Looks like this was fixed upstream. Want to give it a try whether JAX 0.4.37 fixes the issue?

Thanks! seems like the runs are stable now. Though I am doing a 1000-year simulation, so will update here if anything else comes up during the runtime :)

**Comment by dionhaefner** [comment]
Awesome, thanks for reporting back!
